title: "Miyozu"
description: "Miyozu adalah kumpulan link hiburan beragam: dari galau, kocak, sedih, hingga cerita yang bikin baper. Cocok buat kamu yang ingin memilih suasana hati lewat satu klik. Tampilan modern minimalis, ringan, dan mudah diakses kapan saja."
author: "Miyozu"
baseurl: "" 
url: "https://miyozu.github.io"
markdown: kramdown
theme: null

timezone: Asia/Jakarta

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
